### ISSUE TITLE
COPY 也要把别人的配置改掉吧

### ISSUE THREAD

**Issue by dishuihengxin** [spiritLHL/spiritLHL.github.io#1]
![image](https://user-images.githubusercontent.com/20619983/124534725-6b597080-de47-11eb-8bf4-106bae53fa01.png)
兄弟，需要我帮你统一访问么？

**Comment by spiritLHL** [comment]
我hugo生成的public文件，估计是人家改的主题内置生成的

**Comment by spiritLHL** [comment]
没留意，那里的

**Comment by spiritLHL** [comment]
所以说咋弄，下午大把时间

**Comment by dishuihengxin** [comment]
并没有改呢？

**Comment by spiritLHL** [comment]
还没更新。。。我本地的改了。。。这就去更新

**Comment by spiritLHL** [comment]
> 并没有改呢？

改完了，刚刚更新，抱歉

**Comment by dishuihengxin** [comment]
ok，thanks.
